### PR TITLE
Fix 3.8 compatibility 

### PR DESCRIPTION
**Pull request by afbora**

### CODE REVIEW

**Comment by afbora** [comment]
@bastianallgeier I've realized that you've not merged [commit](https://github.com/getkirby/staticache/commit/32400d4d89353a1becbdaee7336ef42b4fa7cfd1) in `develop` branch. Is that still valid?

**Comment by distantnative** [comment]
@lukasbestle tackling this bug in our own plugin, the Value object handling seems pretty harsh here (like too much overhead, the former implementation of just returning the raw value seemed fine). Can we ease this again somehow?

Also makes me think that I am not too much in love with https://github.com/getkirby/kirby/pull/4263 - I think many developers would prefer to handle the raw value for their cache and not have to deal with our wrapper Value object.

**Comment by lukasbestle** [comment]
I agree that getting rid of `Value` in the long term is the best way. It's another one of those hard cases where the current state is really broken ans confusing and we can only get out of this with a rewrite.

I still feel we should go the PSR-16 route in the future. It doesn't make sense to come up with yet another custom caching API.

**Comment by lukasbestle** [comment]
I've included this fix in the refactoring.

**Pull request closed without merging**
